# Configuration preset used on Omu Booby.

[game]
# Hub Information
hostname = "[MRP] Omu Booby ᴱᵁ⁻ᵂ"
desc = "Come join us on Omu Station! A roleplay-centric game focus with the added chaos of Goob antags and more!"

[hub]
tags = "lang:en,rp:med,region:eu_w" # You can find a list of all tags @ https://docs.spacestation14.com/en/robust-toolbox/server-http-api.html#standard-tags
