- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAsakim
  name: Asakim Role
  components:
  - type: MindRole
    roleType: FreeAgent
    subtype: role-subtype-asakim
    antagPrototype: Asakim
    exclusiveAntag: true
  - type: AsakimRole
  - type: RoleBriefing
    briefing: asakim-role-briefing

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleNTAgent
  name: Internals Affairs Agent
  components:
  - type: MindRole
    roleType: NanoTrasen # Omu, was FreeAgent
    subtype: role-subtype-ntagent
    antagPrototype: NTAgent
    exclusiveAntag: true
  - type: NTAgentRole
  - type: RoleBriefing
    briefing: NTAgent-briefing
