- type: loadout
  id: HeadofSecurityGreatCoatDV
  equipment:
    outerClothing: ClothingOuterCoatStasecHoS

- type: loadout
  id: HeadofSecurityLongcoat
  equipment:
    outerClothing: ClothingLongcoatHoS

